### ISSUE TITLE
Css not loading due to plugin folder named wrong

### ISSUE THREAD

**Issue by jessertaylor** [FacetWP/facetwp-time-since#1]
Hi,

I believe the plugin folder is named wrong, as it's installing as facetwp-time-since-master/ 

This causes the css not to load due to hardcoded plugin folder name

```
<link href="<?php echo WP_CONTENT_URL; ?>/plugins/facetwp-time-since/assets/css/front.css" rel="stylesheet">
```

I've done a pull request which uses 

```
plugin_dir_url(__FILE__)
```

To get the path

https://github.com/FacetWP/facetwp-time-since/pull/2

Cheers

**Comment by mgibbs189** [comment]
This has been resolved in the newest version. Thanks for the help, @jessertaylor
