### ISSUE TITLE
Cannot use positive time values

### ISSUE THREAD

**Issue by aaronmak** [FacetWP/facetwp-time-since#3]
There's a bug when I use positive values in the facet.

```
Upcoming Year | +1 year
Upcoming Month | +30 days
Upcoming Week | +7 days
Today | +1 day
Past Week | -7 days
Past Month | -30 days
```

The negative values work well but the positive ones show nothing and the values are wrong. 

You can refer to the screenshots below for more details. 

<img width="352" alt="screen shot 2016-06-03 at 12 04 29 pm" src="https://cloud.githubusercontent.com/assets/3712602/15768526/4e7baa46-2984-11e6-8ff5-e44ea13e5d24.png">
<img width="373" alt="screen shot 2016-06-03 at 12 09 12 pm" src="https://cloud.githubusercontent.com/assets/3712602/15768528/4ef05dfa-2984-11e6-99a1-0b7a858ec2f5.png">
<img width="400" alt="screen shot 2016-06-03 at 12 09 25 pm" src="https://cloud.githubusercontent.com/assets/3712602/15768527/4ee54014-2984-11e6-8dcc-a0951cbf35df.png">

**Comment by mgibbs189** [comment]
It's not a bug, hence the name "Time Since" 😉 

We simply don't support future times (yet), although it's a good idea.
